name: Update README

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Update README.md
        run: |
          # Here you can use any script to update the README.md file
          # For example, let's use a simple Node.js script to append the current date
          echo "Updating README.md"
          node -e "const fs = require('fs'); const date = new Date().toISOString(); let readme = fs.readFileSync('README.md', 'utf8'); readme += '\nLast updated: ' + date; fs.writeFileSync('README.md', readme);"

      - name: Commit changes
        run: |          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README.md with current date'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
