name: Update README

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create update-readme.js script
        run: |
          echo "const fs = require('fs');" > update-readme.js
          echo "const date = new Date();" >> update-readme.js
          echo "const days = ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'];" >> update-readme.js
          echo "const formattedDate = \`오늘은 \${date.getFullYear()}년 \${date.getMonth() + 1}월 \${date.getDate()}일 \${days[date.getDay()]}입니다.\`;" >> update-readme.js
          echo "let readme = fs.readFileSync('README.md', 'utf8');" >> update-readme.js
          echo "readme += \`\\n\${formattedDate}\`;" >> update-readme.js
          echo "fs.writeFileSync('README.md', readme);" >> update-readme.js

      - name: Update README.md
        run: node update-readme.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README.md with current date'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
